# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(897, 503)
        MainWindow.setStyleSheet("QWidget #manualControlWidget\n"
"{\n"
"    border: 2px solid black;\n"
"}\n"
"\n"
"QWidget #typeControlWidget\n"
"{\n"
"    border: 2px solid black;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#F4976C ;\n"
"}\n"
"\n"
"QLabel \n"
"{\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QLabel #userCautionLabel\n"
"{\n"
"    color: #CC383A;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.topWidget = QtWidgets.QWidget(self.centralwidget)
        self.topWidget.setObjectName("topWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.topWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cameraLabel = QtWidgets.QLabel(self.topWidget)
        self.cameraLabel.setText("")
        self.cameraLabel.setPixmap(QtGui.QPixmap(":/img/noimage.png"))
        self.cameraLabel.setObjectName("cameraLabel")
        self.horizontalLayout_2.addWidget(self.cameraLabel, 0, QtCore.Qt.AlignLeft)
        self.infoWidget = QtWidgets.QWidget(self.topWidget)
        self.infoWidget.setObjectName("infoWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.infoWidget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stateStaticLabel = QtWidgets.QLabel(self.infoWidget)
        self.stateStaticLabel.setObjectName("stateStaticLabel")
        self.verticalLayout_2.addWidget(self.stateStaticLabel)
        self.stateDynamicLabel = QtWidgets.QLabel(self.infoWidget)
        self.stateDynamicLabel.setStyleSheet("font-size: 32px;\n"
"color: #838996;")
        self.stateDynamicLabel.setObjectName("stateDynamicLabel")
        self.verticalLayout_2.addWidget(self.stateDynamicLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.cameraIndexLabel = QtWidgets.QLabel(self.infoWidget)
        self.cameraIndexLabel.setStyleSheet("")
        self.cameraIndexLabel.setObjectName("cameraIndexLabel")
        self.verticalLayout_2.addWidget(self.cameraIndexLabel)
        self.horizontalLayout_2.addWidget(self.infoWidget)
        self.verticalLayout_6.addWidget(self.topWidget)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.bottomWidget = QtWidgets.QWidget(self.centralwidget)
        self.bottomWidget.setObjectName("bottomWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.bottomWidget)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.typeControlWidget = QtWidgets.QWidget(self.bottomWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeControlWidget.sizePolicy().hasHeightForWidth())
        self.typeControlWidget.setSizePolicy(sizePolicy)
        self.typeControlWidget.setObjectName("typeControlWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.typeControlWidget)
        self.verticalLayout_3.setContentsMargins(11, -1, -1, 24)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.typeControlLabel = QtWidgets.QLabel(self.typeControlWidget)
        self.typeControlLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.typeControlLabel.setObjectName("typeControlLabel")
        self.verticalLayout_3.addWidget(self.typeControlLabel)
        self.manualPushButton = QtWidgets.QPushButton(self.typeControlWidget)
        self.manualPushButton.setObjectName("manualPushButton")
        self.verticalLayout_3.addWidget(self.manualPushButton, 0, QtCore.Qt.AlignLeft)
        self.autoPushButton = QtWidgets.QPushButton(self.typeControlWidget)
        self.autoPushButton.setObjectName("autoPushButton")
        self.verticalLayout_3.addWidget(self.autoPushButton, 0, QtCore.Qt.AlignLeft)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.typeControlLabelDynamic = QtWidgets.QLabel(self.typeControlWidget)
        self.typeControlLabelDynamic.setObjectName("typeControlLabelDynamic")
        self.verticalLayout_3.addWidget(self.typeControlLabelDynamic)
        self.horizontalLayout_3.addWidget(self.typeControlWidget)
        self.manualControlWidget = QtWidgets.QWidget(self.bottomWidget)
        self.manualControlWidget.setObjectName("manualControlWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.manualControlWidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.topSubWidget = QtWidgets.QWidget(self.manualControlWidget)
        self.topSubWidget.setObjectName("topSubWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.topSubWidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.typeSignalWidget = QtWidgets.QWidget(self.topSubWidget)
        self.typeSignalWidget.setObjectName("typeSignalWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.typeSignalWidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.typeSignalLabel = QtWidgets.QLabel(self.typeSignalWidget)
        self.typeSignalLabel.setObjectName("typeSignalLabel")
        self.verticalLayout_5.addWidget(self.typeSignalLabel)
        self.typeSignalComboBox = QtWidgets.QComboBox(self.typeSignalWidget)
        self.typeSignalComboBox.setObjectName("typeSignalComboBox")
        self.verticalLayout_5.addWidget(self.typeSignalComboBox)
        self.typeSignalPushButton = QtWidgets.QPushButton(self.typeSignalWidget)
        self.typeSignalPushButton.setObjectName("typeSignalPushButton")
        self.verticalLayout_5.addWidget(self.typeSignalPushButton)
        self.horizontalLayout_4.addWidget(self.typeSignalWidget)
        self.areaWidget = QtWidgets.QWidget(self.topSubWidget)
        self.areaWidget.setObjectName("areaWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.areaWidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.areaLabel = QtWidgets.QLabel(self.areaWidget)
        self.areaLabel.setObjectName("areaLabel")
        self.verticalLayout_4.addWidget(self.areaLabel)
        self.areaComboBox = QtWidgets.QComboBox(self.areaWidget)
        self.areaComboBox.setObjectName("areaComboBox")
        self.verticalLayout_4.addWidget(self.areaComboBox)
        self.areaPushButton = QtWidgets.QPushButton(self.areaWidget)
        self.areaPushButton.setObjectName("areaPushButton")
        self.verticalLayout_4.addWidget(self.areaPushButton)
        self.horizontalLayout_4.addWidget(self.areaWidget)
        self.verticalLayout_7.addWidget(self.topSubWidget)
        self.bottomSubWidget = QtWidgets.QWidget(self.manualControlWidget)
        self.bottomSubWidget.setObjectName("bottomSubWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.bottomSubWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.userCautionLabel = QtWidgets.QLabel(self.bottomSubWidget)
        self.userCautionLabel.setStyleSheet("color: #CC383A;")
        self.userCautionLabel.setObjectName("userCautionLabel")
        self.horizontalLayout.addWidget(self.userCautionLabel)
        self.verticalLayout_7.addWidget(self.bottomSubWidget)
        self.horizontalLayout_3.addWidget(self.manualControlWidget)
        self.verticalLayout_6.addWidget(self.bottomWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.stateStaticLabel.setText(_translate("MainWindow", "Поточний стан сигналу на ліхтар:"))
        self.stateDynamicLabel.setText(_translate("MainWindow", "Не визначено"))
        self.cameraIndexLabel.setText(_translate("MainWindow", "Поточна ділянка: None"))
        self.typeControlLabel.setText(_translate("MainWindow", "Виберіть тип керування:"))
        self.manualPushButton.setText(_translate("MainWindow", "Ручний"))
        self.autoPushButton.setText(_translate("MainWindow", "Автоматичний"))
        self.typeControlLabelDynamic.setText(_translate("MainWindow", "Поточний тип керування: Автоматичний"))
        self.typeSignalLabel.setText(_translate("MainWindow", "Тип сигналу"))
        self.typeSignalPushButton.setText(_translate("MainWindow", "Подати сигнал"))
        self.areaLabel.setText(_translate("MainWindow", "Виберіть ділянку:"))
        self.areaPushButton.setText(_translate("MainWindow", "Вибрати ділянку"))
        self.userCautionLabel.setText(_translate("MainWindow", "Ви не можете змінювати параметри! Змініть тип керування."))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
